[package]
name = "simple-redis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "server"
path = "bin/server.rs"

[dependencies]
bytes = "1.4.0"
tokio = { version = "1.28.1", features = ["full"] }
